# Generated by Django 5.2.4 on 2025-08-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(db_index=True, max_length=120)),
                ('tx_ref', models.CharField(max_length=120, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ETB', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=16)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('processor_tx_id', models.CharField(blank=True, max_length=120, null=True)),
                ('gateway_payload', models.JSONField(blank=True, default=dict)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
